#!/bin/bash -e

trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR

chown redis:redis /data

exec chpst -u redis:redis /usr/local/bin/redis-server --dir /data/ --protected-mode no --include '/etc/redis/conf.d/*.conf'
