#!/bin/bash -e

chown redis:redis /data

# Redis versions before 7 do not support wildcard includes.
cat /etc/redis/conf.d/*.conf > /var/run/redis.conf

exec chpst -u redis:redis /usr/local/bin/redis-server --dir /data/ --protected-mode no --include /var/run/redis.conf
